import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'wendeson - dev ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} flex justify-center items-center my-20`}
      >
        <div className="w-full max-w-[700px] md:px-0 px-10 space-y-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
